# Generated by Django 3.2.3 on 2024-04-14 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ref', models.CharField(max_length=14, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_status', models.CharField(max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.company')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
