# Generated by Django 4.2.16 on 2024-09-15 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('batch_number', models.CharField(null=True)),
                ('perishable', models.BooleanField(default=False)),
                ('render_type', models.CharField(max_length=120)),
                ('product_logo', models.ImageField(blank=True, upload_to='paqs/prod_logo/')),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_status', models.CharField(default='Failed', max_length=20)),
                ('QRcode_status', models.CharField(default='Not generated', max_length=20)),
                ('file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.company')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
