# Generated by Django 3.2.3 on 2024-04-17 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='ref',
        ),
    ]
