# Generated by Django 4.2.16 on 2024-09-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='FDA_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='standards_authority_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
