# Generated by Django 5.0.6 on 2024-06-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='batch_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
