# Generated by Django 5.0.6 on 2024-07-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='batch_number',
            field=models.CharField(null=True),
        ),
    ]
