# Generated by Django 5.0.6 on 2024-08-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_expiry_date_payment_manufacture_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='render_type',
            field=models.CharField(max_length=120),
        ),
    ]
