# Generated by Django 5.0.6 on 2024-08-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_render_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='QRcode_status',
            field=models.CharField(default='Not generated', max_length=20),
        ),
    ]
