# Generated by Django 5.0.6 on 2024-08-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_qrcode_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
