# Generated by Django 5.0.6 on 2024-08-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_payment_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_status',
            field=models.CharField(default='Failed', max_length=20),
        ),
    ]
