version: "3"
services:
  server:
    build: &app-build
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_BUILD_VERSION: "3.11"
    environment: &app-environment
      DEBUG: "False"
      RUN_MIGRATIONS: "True"
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      # Postgres params
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_URL: ${DB_URL}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      # Redis params
      REDISHOST: ${REDISHOST}
      REDISPORT: ${REDISPORT}
      REDISUSER: ${REDISUSER}
      REDISPASSWORD: ${REDISPASSWORD}
      REDIS_URL: ${REDIS_URL}
    depends_on: &app-depends-on
      - db
      - redis
    command: /app/deployment/server-entrypoint.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck/"]
      interval: 5s
    ports:
      - 8000:8000

  worker:
    build: *app-build
    environment: *app-environment
    depends_on: *app-depends-on
    command: /PAQSBackend/deployment/worker-entrypoint.sh

  redis:
    restart: unless-stopped
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  db:
    image: postgres:14.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432

volumes:
  postgres_data: {}
