# Generated by Django 4.2.16 on 2024-09-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('code_key', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('batch_number', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('location', models.JSONField()),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('town', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date_time', 'company_name', 'product_name', 'batch_number', 'code_key'], name='product_sca_date_ti_9b3683_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('product_name', models.CharField(max_length=150)),
                ('batch_number', models.CharField(max_length=50)),
                ('code_key', models.CharField(max_length=300)),
                ('perishable', models.CharField(max_length=100)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('message', models.CharField(max_length=255)),
                ('FDA_number', models.CharField(blank=True, max_length=255, null=True)),
                ('standards_authority_number', models.CharField(blank=True, max_length=255, null=True)),
                ('checkout_user_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('checkout_user_phone', models.PositiveBigIntegerField(blank=True, null=True)),
                ('checkout', models.BooleanField(default=False)),
                ('checkout_message', models.CharField(max_length=255)),
                ('patch', models.BooleanField(default=False)),
                ('patch_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('patch_message', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Logproduct',
                'verbose_name_plural': 'Logproducts',
                'db_table': 'LogProduct',
                'managed': True,
                'indexes': [models.Index(fields=['code_key', 'company_name', 'product_name', 'batch_number'], name='LogProduct_code_ke_c7019e_idx')],
            },
        ),
        migrations.CreateModel(
            name='CheckoutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('code_key', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('batch_number', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('location', models.JSONField()),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('town', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date_time', 'company_name', 'product_name', 'batch_number', 'code_key'], name='product_che_date_ti_40bc40_idx')],
            },
        ),
    ]
