# Generated by Django 4.2.16 on 2024-09-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_logproduct_days_to_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logproduct',
            name='days_to_expiry',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
