# Generated by Django 5.0.6 on 2024-08-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_logproduct_qr_key_af7ecf_idx_logproduct_qr_key_fc91bc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logproduct',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logproduct',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
