# Generated by Django 5.0.6 on 2024-08-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_logproduct_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsinfo',
            name='batch_number',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='productsinfo',
            name='render_type',
            field=models.CharField(max_length=120),
        ),
    ]
