# Generated by Django 4.2.16 on 2024-09-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_logproduct_days_to_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutinfo',
            name='key_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logproduct',
            name='key_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scaninfo',
            name='key_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logproduct',
            name='patch_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
