# Generated by Django 5.0.6 on 2024-08-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productsinfo_batch_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logproduct',
            name='checkout_message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logproduct',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logproduct',
            name='patch_message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logproduct',
            name='qr_key',
            field=models.CharField(max_length=300),
        ),
    ]
