# Generated by Django 5.0.6 on 2024-08-18 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_logproduct_logproduct_qr_key_fc91bc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaninfo',
            name='dateNtime',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
