# Generated by Django 5.0.6 on 2024-08-18 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_scaninfo_datentime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scaninfo',
            old_name='dateNtime',
            new_name='date_time',
        ),
        migrations.AddField(
            model_name='checkoutinfo',
            name='date_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkoutinfo',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scaninfo',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
    ]
