# Generated by Django 5.0.6 on 2024-08-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_datentime_scaninfo_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutinfo',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='checkoutinfo',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scaninfo',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scaninfo',
            name='location',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='scaninfo',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
    ]
