# Generated by Django 5.0.6 on 2024-08-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_checkoutinfo_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutinfo',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutinfo',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutinfo',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scaninfo',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scaninfo',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scaninfo',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
