# Generated by Django 5.0.6 on 2024-08-20 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_checkoutinfo_city_alter_checkoutinfo_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutinfo',
            name='batch_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scaninfo',
            name='batch_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
