# Generated by Django 5.0.6 on 2024-08-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_checkoutinfo_batch_number_scaninfo_batch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='logproduct',
            name='checkout_user_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='logproduct',
            name='checkout_user_phone',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutinfo',
            name='location',
            field=models.JSONField(),
        ),
        migrations.AlterUniqueTogether(
            name='checkoutinfo',
            unique_together={('code_key', 'company_name', 'product_name', 'batch_number', 'user_name')},
        ),
        migrations.AlterUniqueTogether(
            name='scaninfo',
            unique_together={('code_key', 'company_name', 'product_name', 'batch_number', 'user_name')},
        ),
        migrations.AddIndex(
            model_name='checkoutinfo',
            index=models.Index(fields=['company_name', 'product_name', 'batch_number', 'code_key'], name='product_che_company_170e23_idx'),
        ),
        migrations.AddIndex(
            model_name='scaninfo',
            index=models.Index(fields=['company_name', 'product_name', 'batch_number', 'code_key'], name='product_sca_company_78cc99_idx'),
        ),
    ]
