# Generated by Django 5.0.6 on 2024-08-22 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_logproduct_checkout_user_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkoutinfo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='scaninfo',
            unique_together=set(),
        ),
    ]
