# Generated by Django 5.0.6 on 2024-08-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_checkoutinfo_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logproduct',
            name='patch_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
