# Generated by Django 5.0.6 on 2024-09-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_logproduct_patch_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsinfo',
            name='company_name',
        ),
        migrations.RemoveIndex(
            model_name='checkoutinfo',
            name='product_che_company_170e23_idx',
        ),
        migrations.RemoveIndex(
            model_name='scaninfo',
            name='product_sca_company_78cc99_idx',
        ),
        migrations.AlterField(
            model_name='checkoutinfo',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scaninfo',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='checkoutinfo',
            index=models.Index(fields=['date_time', 'company_name', 'product_name', 'batch_number', 'code_key'], name='product_che_date_ti_40bc40_idx'),
        ),
        migrations.AddIndex(
            model_name='scaninfo',
            index=models.Index(fields=['date_time', 'company_name', 'product_name', 'batch_number', 'code_key'], name='product_sca_date_ti_9b3683_idx'),
        ),
        migrations.DeleteModel(
            name='ProductsInfo',
        ),
    ]
