# Generated by Django 4.2.16 on 2024-09-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_productsinfo_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logproduct',
            name='FDA_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logproduct',
            name='standards_authority_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
