# Generated by Django 5.0.6 on 2024-08-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_code',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_code'], name='accounts_co_company_6be2b7_idx'),
        ),
    ]
