# Generated by Django 4.2.16 on 2024-09-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_abstractuserprofile_accounts_ab_email_e95a81_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='accounts_us_phone_n_613c4a_idx'),
        ),
    ]
