# Generated by Django 5.0.6 on 2024-08-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_company_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to='static/images/paqs/paqs/comp_logo/'),
        ),
    ]
