# Generated by Django 5.0.6 on 2024-08-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_company_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to='paqs/comp_logo/'),
        ),
    ]
